[package]
name = "tauri-plugin-custom-tabs-manager"
version = "0.0.0"
authors = [ "DreamingCodes" ]
description = ""
edition = "2021"
rust-version = "1.65"
exclude = ["/examples", "/node_modules"]
links = "tauri-plugin-custom-tabs-manager"

[dependencies]
tauri = { git = "https://github.com/simonhyll/tauri", branch = "feat/android-fixes" }
serde = "1.0"
thiserror = "1.0"

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.6" }
